services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "9081:8080"
    volumes:
      - ./open-webui-data:/app/backend/data
    restart: unless-stopped 
  
#volumes:
#  open-webui:
